### PR TITLE
feat: add parser option to throw on duplicate keys

### PR DESCRIPTION
**Pull request by ethanresnick**
This is a PR for #216. Because it's a user opt-in, I don't think it raises any compatibility concerns.

### CODE REVIEW

**Comment by jordanbtucker** [comment]
I like this idea, but I would just treat the second parameter as either the reviver function or an options object rather than add another parameter and have to check for duplicate revivers. Compare this with `stringify` which also treats the second parameter this way.

**Comment by ethanresnick** [comment]
Ok, I’ll update the PR accordingly in a bit

**Comment by ethanresnick** [comment]
PR updated to use the API proposed by @jordanbtucker.

**Comment by ethanresnick** [comment]
@jordanbtucker Can this be merged? If not, what are the blockers?

**Comment by rexxars** [comment]
I'd love to see this landed as well, is there anything we can do to move this along? Any changes needed?

**Comment by jordanbtucker** [comment]
Thanks for the PR. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.

**Comment by vizmathy6** [comment]
A "parser for humans" - in my opinion - should support poor earthlings in detecting their mistakes.
I understand the concept of keeping it simple by not implementing recursion detection (#218) and similar features which can be solved outside the lib or while using the lib anyway, but detecting duplicate keys in the input can only be solved by the parser itself. And while a reference parser is supposed to be clean and elegant over performance-tweaks, it should also show the way in the terms of parsing functionality and the way of passing/handling parse options.
@jordanbtucker please reconsider adding this core parsing functionality to the lib. Currently this is the reference _and_ production json5 library, I don't think creating a json5b or json6 fork should be the way of making json5 even more human (/proof), and as far as I see catalising independently evolving json5 forks wouldn't bring diversity, would only cause chaos and confusion. Don't let json5 become something like RegExp, with independently evolving, incompatible functionality and parameters all around the place in different languages and tools.
Keep showing the way, please.

**Pull request closed without merging**
