### PR TITLE
RFC: add findPointer function

### PR DESCRIPTION
**Pull request by nturley**
This PR adds a function named findPointer which returns the line and column of a JSON element indicated by a JSON pointer.

This allows applications to synchronize between a JSON5 file and the in-memory data structure. For example, this addresses things like #119 where an application determines there is a logical error in the JSON, but it doesn't have enough data to point the user to a line and column number.

JSON Pointers are specified in [RFC 6901](https://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-08).  They are strings that can refer to elements of a JSON document. For example, with a JSON document `{"a":{"b":["c","d"]}}`, the JSON pointer `/a/b/1` would refer to `"d"`.

Tools like [ajv](https://github.com/epoberezkin/ajv) optionally use JSON Pointers to refer to the location where schema validation fails. To get line/column numbers, it's [recommended](https://github.com/epoberezkin/ajv/issues/763) to use [json-source-map](https://github.com/epoberezkin/json-source-map), which wouldn't work for JSON5.

A slightly more complicated alternative to adding this function would be to dump a json source map like [json-source-map](https://github.com/epoberezkin/json-source-map) does. json-source-map additionally spits out the string position of the element and if it's an object, it spits out the key end, value start and value end. That additional information would be enough to address #177, because you could easily find a position to insert additional elements into without disturbing comments or whitespace. I don't believe the format that this tool used is standardized but it seems well thought out.

Another complicated alternative is to dump a javascript source map, so you could use json-source-map along with the emitted javascript source map to find the original line and column number of each symbol.

Another alternative is to fork JSON5 to make a separate tool that can find pointers, but we would have to keep the two parsers in sync, otherwise the in-memory data structure won't match the JSON5 pointers.

So I think this is the easiest way to solve the problem, but I'm open to working on building the entire json source map like json-source-map does.

### CODE REVIEW

**Comment by jordanbtucker** [comment]
Thanks for the PR. Sorry I haven't had a chance to take a close look at this. I like the ideas and the fact that it's based on an IETF RFC, but I'm not sure if it's a good fit for this library.

My main concern is that v3 is going to be another rewrite of the code base, so the code in this PR will need to be refactored for that. I plan on exposing a Lexer/Tokenizer class to help with tools that want more control over parsing JSON5, including the types of tools mentioned in your initial comment.

If we were to implement a `findByPointer` method, I think it would makes sense to put that on a Parser class. That way, the parser could parse the document once, and then `findByPointer` can be called multiple times without requiring the parser to parse the whole document again.

**Comment by nturley** [comment]
Thanks for your feedback!

> If we were to implement a findByPointer method, I think it would makes sense to put that on a Parser class. That way, the parser could parse the document once, and then findByPointer can be called multiple times without requiring the parser to parse the whole document again.

You mean having the Parser object store the location data on every parse? It's several times larger than the source document, so for large documents, I'd expect users to prefer to opt in to storing or emitting location data.

Or are you talking about using callbacks/coroutines/async to allow applications to collect location information from the parser while the document is being parsed?

**Comment by nturley** [comment]
Either way, it sounds like there is a long term plan on how expose location data of the json elements, but not a short term solution. How would you feel if I make new package named json5-source-map which would do basically the same thing as json-source-map but with json5? And the implementation initially will be mostly a copy of this repo, and then after v3 is released, I can use the v3 parser instead of a copy of this one? So in the short term, there would be duplication but in the long term, it would be single-sourced, but the client api would stay the same regardless.

It seems like that would be a good way to address my short term needs and fit in with your long term plans.

**Comment by jordanbtucker** [comment]
> You mean having the Parser object store the location data on every parse? It's several times larger than the source document, so for large documents, I'd expect users to prefer to opt in to storing or emitting location data.

Yes. The user would need to opt in similar to how [Esprima works](https://esprima.readthedocs.io/en/latest/syntactic-analysis.html#node-location).

JSON5 source map is something I'd like to have, so yes, it would be great if you wanted to take that on! 👍

**Pull request closed without merging**
