### PR TITLE
Publish a security policy

### PR DESCRIPTION
**Pull request by jordanbtucker**
This PR publishes a security policy for reporting vulnerabilities as well as linking to it from the README and GitHub issue and pull request templates.

Also fixes a minor typo in the GitHub issue template.

### CODE REVIEW

**Comment by jordanbtucker** [comment]
Maybe I should add `SECURITY.md` to the `files` field in `package.json` since it's referenced in `README.md`.

**Review by aseemk — APPROVED** [review]
Thank you Jordan!

**Comment by jordanbtucker** [comment]
Perhaps we should use this instead of Snyk.

https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

We also wouldn't need anyone to email security@json5.org. It would still be there as a backup, but we should be notified by GitHub.

**Review by ASISBusiness — COMMENTED** [review]
Thanks

**Pull request merged**
