### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by jordanbtucker**
Not sure if there's a reason a license file was never included, but here's one if you want it @aseemk.

### CODE REVIEW

**Comment by jordanbtucker** [comment]
Closes #128

**Comment by ianloic** [comment]
Thanks! The copyright in README.md lists (well links to) other people. How about making tham consistent, and linking to the LICENCE.md from the README.md?

**Comment by aseemk** [comment]
Thanks @jordanbtucker! I was out getting married. =) Cheers.

**Comment by ianloic** [comment]
Congratulations @aseemk!

**Pull request merged**
