### PR TITLE
Update dependencies and support parsing Python-style True/False as true/false

### PR DESCRIPTION
**Pull request by mopatches**
* Updates versions of dependencies to address of bunch of CVEs.
* Adds support for recognizing tokens True => true and False => false, so to improve support for parsing Python's generated pseudo json.
*

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
This seems like a bad idea. If Python is outputting bad json, the library shouldn't blindly accept it because this will have negative downstream effects (see [The Harmful Consequences of the Robustness Principle](https://datatracker.ietf.org/doc/html/draft-iab-protocol-maintenance) for a longer discussion).

**Comment by mopatches** [comment]
Thank you @NoahTheDuke for your quick reply, and the thoughtful reference to the Harmful Consequences of the Robustness Principle doc to help me better understand your point of view.

I was surprised by the negativity of your feedback, given that a primary purpose of the JSON5 library is to be less strict about parsing JSON. But you'd know best in this circumstance.

Would you mind recommending an alternative implementation I could pursue?

For context, while Python is capable of parsing and outputting strict JSON strings it's often the case that users of Python work with list and dict literals that are nearly JSON compatible. One of the bigger differences are bools, where Python uses `True` instead of `true`. So I'd love any insight you're willing to share about how I can update JSON5 to parse strings like `{ "foo": True, "bar": False }` into json.

Thank you again, @NoahTheDuke.

**Comment by NoahTheDuke** [comment]
To be clear, I'm not a maintainer and have never contributed to this library, I'm just voicing concern as someone who uses the library and cares about internet standards.

For your purposes, why not convert to json using one of Python's libraries?

**Comment by jordanbtucker** [comment]
Thank you for the contribution and the time and effort you put into this. However, I'm hesitant to merge this. This library is reference parser for the [JSON5 format](https://spec.json5.org/), so I think it would be surprising for users to have it start parsing documents that aren't valid JSON5.

**Comment by jordanbtucker** [comment]
Regarding the CVEs, this library has no runtime dependencies, so they are all from dev dependencies. The current version (v2) still supports Node.js back to v6, so updating the dev dependencies at this time is problematic.

These issues are resolved in the v3 branch, but v3 hasn't been released yet.

**Pull request closed without merging**
