### PR TITLE
Minor corrections to README.md

### PR DESCRIPTION
**Pull request by brandondavid**
This is a repeat of an earlier fix that was recently overwritten.  See the following commits:
346a5de
f099c7d

### CODE REVIEW

**Comment by jordanbtucker** [comment]
Where is the link broken? It looks fine on GitHub and npm.

**Comment by brandondavid** [comment]
I found a similarly broken link further down the page, as well as some other problems stemming from f099c7d.

The issue is that `README.md` in _**master**_ and `index.md` in _**gh-pages**_ were being updated somewhat independently from each other, so when the latter was overwritten with the former, several commits were effectively lost.

**Comment by brandondavid** [comment]
And just for the record, this is how the "link to Crockford's parser" looks (to me) on https://json5.org using Chrome or Firefox:

**Comment by jordanbtucker** [comment]
Oh, I see. I didn't realize you were talking about https://json5.org. I just fixed these issues with this commit.

253bee2cede2fc477681f1fae4532795fea8952e

**Comment by brandondavid** [comment]
Looks great!  That's certainly a good solution for 0bc5ca4 and b2641e3.

But you may want to take another look at baad278 and 0f926d0.  The first paragraph of https://json5.org is still linking to the old RFC and the "link to license" gives a 404 because it's relative instead of absolute.

**Comment by jordanbtucker** [comment]
Sorry, I've got too many things going on tonight. I should have taken a closer look at the PR. Then again, the scope of this PR has been growing.

Rather than change the link to the LICENSE file, I'd rather just pull the file into the gh-pages branch and leave the link as is. Modifying the README every time I update it on the gh-pages branch is not desirable. And the reason I don't want to fix the links in the README is because the lines get automatically wrapped by the editor, so they're just going to get wrapped again eventually.

I would like to update the RFC link and give you credit. Can you update the PR so that it only includes that change? Thanks.

**Comment by brandondavid** [comment]
Done!

Reverted the unneeded commits and adjusted the PR title to reflect its final scope.

**Comment by jordanbtucker** [comment]
Thanks. I squashed the commits and rebased on the v2 branch, so this PR didn't get automatically merged. I'm pushing to the master branch only when a new release is published. You can see your commit at b20d319f84352927e00b584eac21c9492dea75cf.

You'd need to rebase your master branch off of the v2 branch and push in order for GitHub to close the PR automatically. It's probably better to create a feature branch for PRs instead next time. Thanks again!

**Pull request closed without merging**
